repos:
- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.12.0
  hooks:
  - id: pretty-format-golang
    args: [--autofix]
  - id: pretty-format-yaml
    args: [--autofix, --indent, '2']
    types: [file]
    files: \.(yaml|yml|manifest)$
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
  - id: end-of-file-fixer
  - id: check-added-large-files
    args: [--maxkb=1000]
  - id: check-docstring-first
  - id: check-ast
  - id: check-executables-have-shebangs
  - id: check-shebang-scripts-are-executable
  - id: pretty-format-json
    args: [--autofix]
  - id: mixed-line-ending
    args: [--fix=lf]
- repo: https://github.com/jumanjihouse/pre-commit-hooks
  rev: 3.0.0
  hooks:
  - id: shellcheck
  - id: shfmt
    args: [-i 2 -ci -bn]
